package com.springSQLConnection;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity // annotation marks the class as a JPA entity, It means that this class will be mapped to a database table. By default, the table name will be the same as the class name, but this can be customized.
public class Civillian {
	
	@Id		// primary key for this entity + no need to @Column annotation (it happens automatically
	@GeneratedValue(strategy = GenerationType.IDENTITY)		// primary key value will be automatically generated by the database (typically used with auto-increment columns).
	private int id;
	@Column(name = "emp_name")
	private String name;
	@Column
	private float tax;
	
	//default constructor
	public Civillian(String name, float tax) {
		super(); // calling / extending parent class, here its extends java.lang.Object 
		this.name = name;
		this.tax = tax;
	}	// this is responsible to create new instances in future
	
	
	// Creating all Field Getters & Setters
			// id Getter Setter
			public int getId() {
				return id;
			}
			public void setId(int id) {
				this.id = id;
			}
			// name Getter Setter
			public String getName() {
				return name;
			}
			public void setName(String name) {
				this.name = name;
			}
			// tax Getter Setter
			public float getTax() {
				return tax;
			}
			public void setTax(float tax) {
				this.tax = tax;
			}
}
